name: Croffle

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer/
          tags: test-image:latest
          push: false
          load: true

      - name: Docker Run
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          options: --rm -v ${{ github.workspace }}/sites-available/:/etc/nginx/sites-available/ -v ${{ github.workspace }}/nginx.conf:/etc/nginx/nginx.conf -p 3000
          run: service nginx start

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Playwright
        working-directory: .croffle/test
        run: |
          pnpm install --frozen-lockfile
          pnpm dlx playwright install
          pnpm dlx playwright install-deps

      - name: Run test
        working-directory: .croffle/test
        run: pnpm dlx playwright test

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: .croffle/test/playwright-report/results.json
