name: Croffle

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer/
          tags: test-image:latest
          push: false
          load: true

      - name: Docker Run
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          options: -v ${{ github.workspace }}/sites-available/:/etc/nginx/sites-available/ -v ${{ github.workspace }}/nginx.conf:/etc/nginx/nginx.conf
          run: echo "hello world"
